### ISSUE TITLE
Format problems

### ISSUE THREAD

**Issue by pbill2003** [alistairbill/evohome-charts#4]
Als

I have a problem with evohome server not recognizing a schedule written by the 'evohome configurator'. By 'not recognizing' I mean that the schedule I imported wasn't reflected in the schedule on the Evohome thermostat in the front room at 35MR or the Honeywell app. This despite no errors apparent during the import process. There are setpoints missing in the temperature schedule, despite them being visible on inspection of the schedule file produced by the configurator. 

So ..... to debug I compared a schedule file coming from evohome & a schedule file from the configurator. I hoped these would 

I hope this picture illustrates. Configurator file on the right. It appears that the configurator writes colon-space-square or curly bracket-linefeed. Whilst evohome writes colon-space-linefeed-a few tabs-square or curly bracket-linefeed

![image](https://user-images.githubusercontent.com/72416238/96028841-c24e8e00-0e51-11eb-9108-f16aa77189b9.png)

I suspect that although this format difference doesn't change the schedule - a parser probably doesn't really care about this. But it does make it almost impossible to debug if I'm looking for problems.

What d'you reckon? Could you alter please?

**Comment by alistairbill** [comment]
I'd suggest the problem is a dodgy JSON parser in the evohome command line tool you're using. Can you try changing a known good config file, so we know what the parser accepts?

- Does it work if you change all the tabs to spaces?
- Does it work if you remove spaces before the colons?

If it's some quirk like the above (the parser only accepts tab-indented files, for example), I can fix pretty easily

**Comment by pbill2003** [comment]
OK so the parser isn't fussy. So no changes needed. 

RTFM ... Evohome supports a maximum of 6 setpoints per day. Sorry.
